### ISSUE TITLE
[Feature] User instructions for sending messages

### ISSUE THREAD

**Issue by LarsRedCross** [rodekruis/cashpo#1]
**Is your feature request related to a problem? Please describe.**
CVA verification team needs to have some explainations on how to send messages. Training was given on this in Greece but they also need something they can look back to. 

**User Story**
As a CVA verification team
I want to have materials on how to send messages
So that I can check them when convenient for me

**Describe the solution you'd like**
Create a slide-deck, video or image on how to use it in such a way that it can be easily reused in future projects. It should be the same format that we can use for all instruction/manuals. 

**Additional context**
Take into account that not everyone speaks English, it would be nice if we can make it in such a way that it is easily translatable. But that can also be a later slice and would be something we could want for all instruction manuals.

**Comment by tijsziere** [comment]
@LarsRedCross I've created a manual and placed it [here](https://github.com/rodekruis/cashpo/tree/main/Manuals). Please close this issue if satisfied!
