### ISSUE TITLE
[SPIKE] limit Greece-wide access on data of Individuals, Visits and Vaccines

### ISSUE THREAD

**Issue by corina444** [rodekruis/cashpo#105]
**Functional or Technical Spike**
Functional are used to analyze overall solution behavior (more [info](https://www.scaledagileframework.com/spikes/))

**User Story**
As a NLRC and HRC HQ staff
I want to limit access to the database of the registered individuals 
So that I ensure the HRC staff/volunteers working in different locations in Greece "do no harm" while using the CRM system by having access to the data of the people affected.

**Acceptance Criteria**
- Comment below what the most straightforward solution could be. 
- Please do so before 30th of June so we can take the implementation with us in this sprint still

Things I thought about:
1. users can't view the entire database but retain ability to search the entire database. Only IT can see entire database. 
2. we restrict access to be location-specific. This could be tricky because people very regularly move from one HRC location to the other.

**Timebox**
1,5h

**Comment by tijsziere** [comment]
Have a look into "teams", we could give people access to only the records related to their team, and a team could be a location. Then we can give people access to all people, but just on a name basis by creating a role and configure this on a per field basis -> scroll down when creating a role.

**Comment by corina444** [comment]
After discussion with HRC and later with Laura the possible solution is:

Add location specific filter:

1. Add the field "Location" to individual profile. 
2. Add a default filter for all search options to limit to user location.
3. If user wants to check at other location, temporarily disable location filter and search whole database.

Medical staff (doctors & nurses) can see Individual profile, Medical information, Visits and Vaccines. 
Registration desk officers can see Individual profile. 

This solution, in combination with removing the "Vulnerabilities" section and anonymizing it, is already a step forward. 
HRC are hesitant to implement a "checkpoint" to request the addition of a patient to a location group, as it can introduce many delays for medical procedures and planning of patient visits. 

@LauraMedendorp will check if this is possible.

**Comment by tijsziere** [comment]
What harm is there if the registration desk has access to all of them, but doctors & nurses only to those of their location? With the above functionality someone malicious is able to do whatever they want to do anyway. So its either only location or all of them. A filter doesnt change much in terms of protection.

A middle ground could be to give 1 individual per location this power.

**Comment by tijsziere** [comment]
a middleground option could be to create an additional entity, with a live-copy of the patients entity and just copy the name and location that is accessible to all. That might actually be the best option

**Comment by tijsziere** [comment]
Implemented. @corina444 please test with different users.

**Comment by corina444** [comment]
@tijsziere I made two new users, one registration desk officer under the Lesvos team and one medical staff under the Lesvos team. Neither can look up people outside the Lesvos team to change their location to Lesvos. Is this something we can solve together?
