### ISSUE TITLE
[SPIKE] restructure medication section to enable multiple medications

### ISSUE THREAD

**Issue by corina444** [rodekruis/cashpo#107]
**Functional or Technical Spike**
Technical are used to research various approaches in the solution domain (more [info](https://www.scaledagileframework.com/spikes/))

**User Story**
As a HRC doctor
I want to have the option to add more than one medication 
So that I can prescribe multiple medications in one visit.

**Acceptance Criteria**
Right now a doctor can only add one medication per visit. We would like to enable the option to add multiple medications in one visit. We want to know how it's best to address this, by thinking about a smart technical solution. Perhaps make the medication an entity on it's own and put it in the Visits section? The acceptance criteria would be 
- a new, [feature] ticket which asks for the technical solution to be realized.
- starting issue #126 

**Timebox**
2-3 hrs

**Comment by tijsziere** [comment]
possible, just needs work to implement correctly

**Comment by tijsziere** [comment]
Implemented
