### ISSUE TITLE
[BUG] Medical information not showing when opening the profile of an individual

### ISSUE THREAD

**Issue by corina444** [rodekruis/cashpo#109]
**Describe the bug**
Right now I open the page of an individual and I can only see the information entered in the section "Medical information" if I edit the option "Do you want to fill in the medical information". It should be visible at all times. 

**To Reproduce**
1. Go to the profile of an individual
2. Scroll down to the section "Medical information"
3. Edit the option "Do you want to fill in the medical information" to enable click the box. 
4. See current medical informaiton that is there, but not shown in the section.

**Expected behavior**
We should be able to see the medical info. 

**Screenshots**

![Screenshot 2022-06-21 at 10 54 32CEST](https://user-images.githubusercontent.com/60880112/174759611-fe2f2524-5112-4b62-b253-660160f95114.png)

![Screenshot 2022-06-21 at 10 54 59CEST](https://user-images.githubusercontent.com/60880112/174759684-e40ae9e7-2a7e-4c3c-8c8d-9ff6fd4e5b30.png)

**Comment by tijsziere** [comment]
Remove boolean field and always show the med info to the doctors
