### ISSUE TITLE
[SPIKE] restructure "Vulnerabilities" section for maximum data privacy

### ISSUE THREAD

**Issue by corina444** [rodekruis/cashpo#124]
**Functional or Technical Spike**
Functional are used to analyze overall solution behavior (more [info](https://www.scaledagileframework.com/spikes/))

**User Story**
As a HQ staff
I want to uncouple the vulnerability information from the individuals
So that I can safely use the information for statistics in reports

**Acceptance Criteria**
- A clear plan written in the comment on how to structure a system (can be within the crm system or not) to gather the vulnerability data. The plan should consider that it's best to not couple the vulnerability data at all to the Individuals. What we want:
             1. collect the vulnerability data upon registration but not link it to individuals. 
             2. check if it's a possibility to edit the information we gather. E.g. someone comes and says "now I found a job so I am not unemployeed any more". Is there any way we can change this? Or not, and do we just need to accept we can't do this?
- Please include alternative options you considered and the reasons that you chose the current plan. 
- Please do so bbefore 30th of June so we can take the implementation with us in this sprint still
- I will consider the plan and create a new feature request for it

**Timebox**
2-3 hrs

**Comment by tijsziere** [comment]
@LauraMedendorp, proposal:
- only collect this data during registration
- then copy info to a new unrelated entity, making use of formulas (https://docs.espocrm.com/administration/formula/#recordcreate)
- delete the original information from the profile and do not display in the layout

**Comment by corina444** [comment]
After discussion with HRC and later with Laura the possible solutions are:

1. Register vulnerabilities during a Visit (under visit entity) > Save > Copy the information to an anonymous entity > delete vulnerability data from the visit. --> This way it is not a snapshot and the health team can monitor their numbers per visit instead of per registration.
2. Register vulnerabilities upon registration in EspoCRM > delete vulnerability data from the Individual. --> This way shows a snapshot of the data upon registration only. 
3. Register vulnerability data upon at the registration desk OR medical staff when individual comes in for a visit, by using a Kobo form. --> This way it is not a snapshot and the health team can monitor their numbers per visit instead of per registration. The drawback is the patient has to tell their vulnerabilities to a registration desk officer (not ideal) and that it's a form, not using the system.
