### ISSUE TITLE
[Feature] Remove dashboard from CRM system

### ISSUE THREAD

**Issue by corina444** [rodekruis/cashpo#125]
**Is your feature request related to a problem? Please describe.**
The dashboard should only be accessible by IT staff and reporting staff. It doesn't need to be accessible in the crm system.

**User Story**
As a HRC IT staff or reporting staff
I want to access the dashboard information
So that I ensure maximum data protection of the information by not sharing it with any users within the crm system

**Describe the solution you'd like**
1. Remove the dashboard from the crm system
2. Restrict the access by locking the dashboard behind a password 
3. Post in a comment under this ticket the link to access the dashboard and send me the password privately
4. Post in a comment under this ticket how the landing page should look like.

**Comment by tijsziere** [comment]
done

**Comment by corina444** [comment]
Awesome, can you post the link to the dashboard in our HRC health channel so I know how to find it @tijsziere ?
