### ISSUE TITLE
[Feature] update dashboard to contain report indicators

### ISSUE THREAD

**Issue by corinamarkodimitraki** [rodekruis/cashpo#152]
**User Story**
As a HRC health team lead
I want to see the latest numbers on the relevant indicators in the dashboard
So that I can report easily and quickly.

**Describe the solution you'd like**
Please include the most relevant indicators as seen in the 2 reports in the teams folder CashIM Greece > HRC health > 02_Dashboard 
As an example, see https://go.ifrc.org/emergencies/5425#data

**Comment by leoniecazemier** [comment]
One last thing we need to do is update the database link to the new HRC server, and update the API key, in the pbi file.
