### ISSUE TITLE
[BUG] non-admin user not able to change individual location

### ISSUE THREAD

**Issue by corinamarkodimitraki** [rodekruis/cashpo#155]
**Describe the bug**
When logged in as medical staff in Lesvos, and I search for an individual outside of Lesvos and change their location, this change is not processed and the location doesn't change. I am able to do this change as an administrator.

**To Reproduce**
1. Log in system as non-admin user (create user and link with 2FA to your phone and choose one of the locations are your base) 
2. Global search for individual outside your location
3. Change location to your own.
4. Click on name of individual.
5. See error. 

**Expected behavior**
When changing the location of an individual to match your own location, the location change should be processed and you should be able to see their profile. 
Right now as a doctor in Lesvos I can change the location but then I can't enter the profile of the individual.
When I log in as an admin and check this person's profile I see the location change actually didn't go through and it's still set to the initial location.

**Comment by leoniecazemier** [comment]
This seems to work alright now. Let me know if it is not the case.
