### ISSUE TITLE
[Feature] Import dentist treatment data

### ISSUE THREAD

**Issue by leoniecazemier** [rodekruis/cashpo#168]
**Is your feature request related to a problem? Please describe.**
The KOBO form for dentist visits includes treatment fields. These are currently not implemented in Espo. 

**Describe the solution you'd like**
We need to find out whether this information needs to be imported, and, if yes, create the fields in Espo and import the dentist treatment data.

**Comment by corinamarkodimitraki** [comment]
Asked today to the HRC health team how to import dentist data. Add the treatment to the notes in diagnosis.

**Comment by corinamarkodimitraki** [comment]
In yesterday's meeting with the HRC health leads, they told me the treatment info of the dentist can be put in the Notes field in diagnosis @leoniecazemier .
