### ISSUE TITLE
[Feature] unique HRC code counter 

### ISSUE THREAD

**Issue by corinamarkodimitraki** [rodekruis/cashpo#174]
**Is your feature request related to a problem? Please describe.**
Multiple registrations happen at the same time -> sometimes it can be confusing which code to use. 
We want to see fast what code to use for our registration. 
We want each code to be used only once, and the system to not allow to use the same code twice.  

**User Story**
As a [user]
I want to [action]
So that I [reason]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by corinamarkodimitraki** [comment]
@corinamarkodimitraki check with HRC health how important the prefix of the location in the HRC code is to them. Is it necessary?

**Comment by corinamarkodimitraki** [comment]
The health team uses the 3-letter code to know where the person was first registered. This is the only information they get out of it. If we remove the 3-letter code, we have to make sure they can still find the original registration location. 

Perhaps we can create a new field in the entity "Individuals" which will automatically inherit the location of the user that is registering the person. Each user, depending on their location, is assigned to a Team. The Team has the name of the location. 

If we make a new field whose value (location) is automatically inherited from the user making the registration and locked so as to not be changed in the future anymore, we solve this issue.

**Comment by angelinaRC** [comment]
9digits
Team of the user
Duplicates
Field type
Separate field - Initial location of the registration - one time added

**Comment by angelinaRC** [comment]
ifThen(uniqueID == null, uniqueID = codeHRC);

**Comment by corinamarkodimitraki** [comment]
The codes the their corresponding locations:

ΑΤΗ>EHS Athens
ΚΟΥ>Mobile Health Team
ΕΥΛ>EHS Ano Liosion
ΚΑΛ>EHS Kallitheas
ΚΟΡ>Korinthos Clinics
ΜΑΛ>Malakasa Clinics

**Comment by angelinaRC** [comment]
There is now an additional field, locationRegistration that records the location of the user creating a new patient. It does not change even if the location of the patient is updated.

Also, for the existing patients, we can update their data by first adding the Location Registration in csv and importing the data afterwards.

**Comment by corinamarkodimitraki** [comment]
We have to make sure we will update the dashboard accordingly. Registrations will be linked to the original location of registration, while visits and vaccinations need to be linked to the "current location".

**Comment by angelinaRC** [comment]
1. Create number (auto-increment) field called codeHRC
2. Add to formula 
```
//add a unique code that either autoincreases or get the old value
ifThen(uniqueID == null, uniqueID = codeHRC);
```
3. Add locationRegistration field
4. Add to formula 
```
//creates a field that registers the initial registration location
$locregname = record\attribute('Team', array\at(teamsIds, 0), 'name');
ifThen(locationRegistration == null, locationRegistration = $locregname);
```
5. Create codeHRC field in Contact Check
