### ISSUE TITLE
[Dashboard] medications with invalid social security number

### ISSUE THREAD

**Issue by corinamarkodimitraki** [rodekruis/cashpo#176]
**Is your feature request related to a problem? Please describe.**
I want to be able to show how many people without a valid AMKA/PAMKA/PAYPA (social security number) received medication. 

Use option under medications with checkmark "invalid AMKA"

**User Story**
As a HRC health lead
I want to see how many medications were given to people with an invalid VS with a valid social security number (AMKA/PAMPA/PAYPA)
So that I can report on it

**Describe the solution you'd like**
Add a number box in the Medications page of the dashboard showing number of medications given to individuals with valid social security number VS invalid/no social security number.

**Comment by angelinaRC** [comment]
@corinamarkodimitraki  I had a look into the data and I don't see the social security number anywhere in powerbi. Probably it is because it's PII data so we don't load it. We would have to discuss what's the best way to do it.

**Comment by corinamarkodimitraki** [comment]
Since I adjusted espo, perhaps we need to renew the API connection or so, so that the new options & data are loaded in PowerBI? Let's discuss in our meeting

**Comment by corinamarkodimitraki** [comment]
Check again with HRC. @corinamarkodimitraki

**Comment by corinamarkodimitraki** [comment]
As per my call with the health team today, we don't have to show medications,there should be an option in the visit in Espo to add if the person has a valid social security number or not. Then we would have to link this to dashboard and put it in the page "Visits". Whenever someone presses the number showing the unique individuals, it should show how many of them had valid and how many invalid social security number.

**Comment by corinamarkodimitraki** [comment]
Closed this and opened ticket to add valid or invalid AMKA/PAMPA/PAYPA in visit as checklist #224
