### ISSUE TITLE
[Feature] Data Import Ano Liosion

### ISSUE THREAD

**Issue by leoniecazemier** [rodekruis/cashpo#190]
Forms to use: 
- BHU_registration --> not same as athens
- Visits + medications --> visits not same, medication same as athens
- Vaccinations --> Same as athens

**Comment by corinamarkodimitraki** [comment]
@leoniecazemier can you, along with this data, import data of the MHT from 8-19 december as well? Unfortunately Dimitra didn't understand that they shouldn't be using kobo once everyone is trained, and so some people still used Kobo. If not possible, they will have to add this to the system manually (I don't think it would be a lot of people). Please let me know if you think this is doable or not, then I can inform the HRC health team. Thanks!

**Comment by corinamarkodimitraki** [comment]
Add the data of 15/16 in espo by hand?

**Comment by corinamarkodimitraki** [comment]
Made "import student health check" a new ticket for all locations so we can close this @leoniecazemier
