### ISSUE TITLE
[Feature] Data import mobile health team

### ISSUE THREAD

**Issue by leoniecazemier** [rodekruis/cashpo#191]
Split in MHT/other locations: 

Forms to use MHT: 
BHCU registration MHT --> Same as athens
BHCU_visits --> only for MHT! not sure if same as athens
Vaccination --> Column G merge options all are MHT
student health check (MHT) --> new

Other locations are: 
Nea Kavala
Ritsona
Malakasa
Korinthos
Serres
Lesvos
Koy (new MHT, old form, different)

Forms to use other locations:
Registration_....--> not same as athens - it has field of location
Visits_.... --> not the same as athens  (KOY = MHT code)
Vaccination_.... -> not the same as athens
student health check_....--> new

**Comment by leoniecazemier** [comment]
Done: 
Import bulk of data from registrations, visits/medications and vaccinations forms.
Importing data from last 2 weeks before training

To do: 
Importing data from new form: student health check

**Comment by corinamarkodimitraki** [comment]
I am closing this since you are done, and I moved "import student health check" to new ticket.
