### ISSUE TITLE
[Dashboard] Separate registered individuals from beneficiaries 

### ISSUE THREAD

**Issue by leoniecazemier** [rodekruis/cashpo#194]
Currently the dashboard 'individuals' page reports on unique (newly) registered individuals (per year/month)
The HRC staff also needs to report on unique beneficiaries per year/month, i.e. how many unique people have visited at the location in a certain time frame. 
We need to update the dashboard so that it includes per month/year:
 - Total number of unique people registered 
 - number of new registrations
 - number of unique people that visited.   (i.e. 2 visits by the same person in the same month are 1 unique beneficiary in that period)

**Comment by corinamarkodimitraki** [comment]
This is included in the dashboard, under the graph "Known individuals" and "Unknown individuals" in each page. Therefore I am closing this issue.
