### ISSUE TITLE
[Dashboard] Add visit duration

### ISSUE THREAD

**Issue by leoniecazemier** [rodekruis/cashpo#202]
*User story*
As a HRC health lead
I want to know the average duration of visits at the dentist and mental health clinics
So I can report on them 

*Describe the solution you'd like*
Add a small box which shows the average visit duration for the dental and mental health clinics in the visits page of the dashboard. The visit duration is a field in Espo under the entity "Visit" and is a mandatory field for both the dental and the mental health clinic.

**Comment by angelinaRC** [comment]
@corinamarkodimitraki and on another note - there are also plenty of negative values for other clinic types. Maybe we should check why is that so.

**Comment by corinamarkodimitraki** [comment]
Check with client, do they put the correct data? Dentists should check their data. Do they want us to filter entry or just encourage the dentist to put the right data.

**Comment by corinamarkodimitraki** [comment]
On 2023.01.19 I discussed with the health team of HRC and they will retrain the dentists to enter the correct duration in the system.
