### ISSUE TITLE
[BUG - Dashboard] EHS Athens registrations not matching

### ISSUE THREAD

**Issue by corinamarkodimitraki** [rodekruis/cashpo#204]
**Describe the bug**
Ntina, head of EHS Athens checked the number of new registrations in the dashboard and the numbers they have on paper. November shows 208 new registrations but true number on paper is 119. Can we check this?

**Comment by leoniecazemier** [comment]
I think what happened is, some people I had no known registration date, so I put it to the date of importing. I'm not so sure how we could fix it.. We could think about it but perhaps we need to accept that the dates around data import are a bit messier.
