### ISSUE TITLE
[BUG - DASHBOARD/ESPO] imported november data not showing

### ISSUE THREAD

**Issue by corinamarkodimitraki** [rodekruis/cashpo#206]
**Describe the bug**
Ntina says that the dental and pathologist visits that took place in the first weeks of November before the pilot, are not showing up in the dashboard. Perhaps not in espo?

**Comment by leoniecazemier** [comment]
Hmm yes it seems like we missed some data, perhaps we could redownload the data from 2-20 nov, and import it. 
![image](https://user-images.githubusercontent.com/17046096/205330448-0c0184bc-7ac2-4439-aaac-524c891bf054.png)
