### ISSUE TITLE
[Dashboard] update clinic types in dashboard to match espo

### ISSUE THREAD

**Issue by corinamarkodimitraki** [rodekruis/cashpo#215]
This is issue No. 7 in the Excel "HRC Health Tickets Tracker.xlsx"

**Is your feature request related to a problem? Please describe.**
We added some clinic types e.g. cardiological were added during the pilot in espo, but this was not adjusted in powerbi.

**Describe the solution you'd like**
We want all the clinic types to show in the Visits page of the dashboard.

**Comment by angelinaRC** [comment]
and same here - I see that (at least cardiological) is in there. 
![image](https://user-images.githubusercontent.com/62642010/210744798-cb6ef7f6-4fbd-416a-b6cc-9d4f465af5bb.png)

Could you send me the whole list so I can check?

**Comment by corinamarkodimitraki** [comment]
Cardiological
Dental
Gynecological
Mental Health
Nursing Station
Ophthalmologic
Orthopedic
Paediatrics
Pathological
Pneumonological

**Comment by angelinaRC** [comment]
ok, will change Psychiatric to Mental Health. 

There is quite a few "Unknown" clinic types entries, do we leave them like this?
And there is one School Hygiene (probably old entry)? what do we do with it?

![image](https://user-images.githubusercontent.com/62642010/210775927-8db8822e-1c47-4f23-be9d-895c2cfc24d4.png)

**Comment by corinamarkodimitraki** [comment]
Hmm, not sure about the "Unknown". How many are there? Is there a way to know what they entail? Maybe we should look in Espo?

**Comment by corinamarkodimitraki** [comment]
I cannot find the "School Hygiene" entry in Espo, but I would leave it out since School hygiene is not part of the clinic types anymore.

**Comment by angelinaRC** [comment]
there are 7808 unnknown rows. Might something went wrong during import?

**Comment by corinamarkodimitraki** [comment]
I imported some data last week, but I indeed got some errors for about 6,000 rows. But I am not sure if this is the same as what you mention here. Let's discuss in our meeting tomorrow/next week.

**Comment by corinamarkodimitraki** [comment]
Unknown clinic type has to do with the change in options of clinic type in Espo. Solution is to match options of unknown clinic visit entries to the existing ones and then import again. Keep open for now

**Comment by corinamarkodimitraki** [comment]
We will not invest time into changing the clinic type option of past visits that don't match the current ones. HRC health chose to not change this, since they anyways will need to be reporting on new visits, in 2023.
