### ISSUE TITLE
[Feature] change vaccination suppliers shown, to match espo options

### ISSUE THREAD

**Issue by corinamarkodimitraki** [rodekruis/cashpo#219]
**Is your feature request related to a problem? Please describe.**

**User Story**
As a [user]
I want to [action]
So that I [reason]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by corinamarkodimitraki** [comment]
I asked HRC health to check the list before (the one that is still in the dashboard) and after the pilot (the one that is in espo) and then check which vaccine entry should be named how. Ioanna made the list and sent me the picture below.

![07ac0243-ca64-4e82-b6cf-2026f346dbef](https://user-images.githubusercontent.com/60880112/213704719-ec79807d-e8a4-4760-9543-52d5ef277223.jpeg)

**Comment by corinamarkodimitraki** [comment]
Can you check @angelinaRC  if the axis table for vaccination suppliers matches the list below? (which are the options in espo). If yes, you can close the ticket. If no, can you please update the axis table in the dashboard to match these options? 

**Options**
Ministry
HRC
Prescription HRC
Private

**Comment by corinamarkodimitraki** [comment]
As per my call with the health team today, we don't have to make the past entries make sense, since they don't have to report on it. So we only need to update the axis table in the dashboard to match the current options so all 2023 entries are shown.

**Comment by angelinaRC** [comment]
@corinamarkodimitraki I just checked again, and we don't have axis table for vaccines suppliers and for 2023 there are three options (HRC, Prescription HRC, Private). So there is no need to change anything on this ticket. Or did I forget something?

**Comment by corinamarkodimitraki** [comment]
Ah you are right! Ok I will close this ticket! thanks Angelina
