### ISSUE TITLE
[SPIKE] New entity family members

### ISSUE THREAD

**Issue by corina444** [rodekruis/cashpo#23]
**Functional Spike**
Functional are used to analyze overall solution behaviour (more [info](https://www.scaledagileframework.com/spikes/)).

**User Story**
As a registration desk user
I want to link individuals e.g. a mother to a daughter
So that the health provider can use these insights to provide further medical services. 

**Acceptance Criteria**
Decision: is this feasible from a technical point of view? 
If yes: 
1. create visualization of architecture/data model. 
2. create follow-up issue to implement this model. 

**Timebox**
Describe how much time we should spent on this spike.

**Comment by LauraMedendorp** [comment]
I created a many-to-many relationship for individuals, named the 'left-side' Parents and 'right-side' Children and added this to the layout. If you now add a parent to a individual, this parent automatically has this individual as child.

**Comment by corina444** [comment]
I checked this and indeed it looks great Laura, well done!! I renamed the section to "Family of the individual" to make it more general instead of "Children of the individual".
