### ISSUE TITLE
[Feature] Dropdown list to select clinic type 

### ISSUE THREAD

**Issue by corina444** [rodekruis/cashpo#41]
**User Story**
As a HRC health provider
I want to select the clinic type where I am currently working from a dropdown list
So that I don't have to look into an extra window that opens up but find the option easily. 

**Describe the solution you'd like**
Change the selection Clinic Type to dropdown list.

**Comment by LauraMedendorp** [comment]
I think we have to change the type of this field to enum or multi-enum to be able to make it a dropdown. I will discuss with Fernando

**Comment by LauraMedendorp** [comment]
Removed the clinic type as entity but added is as field of Visit. The links that ClinicType had are removed, but according to Tijs this should not provide any problems. 
I added the ClinicTypes options out of this file. Please check if this is correct and complete. https://rodekruis.sharepoint.com/:x:/r/sites/team-Cash-IM-Greece-510/_layouts/15/guestaccess.aspx?guestaccesstoken=H31Z4wUdYlrH5eE%2FLuFhKrHoMyAaYJuS3AumabZdWL8%3D&docid=2_0c14a9a1de26846bfb981dfaf669c89b7&rev=1&e=xHHnUX

**Comment by corina444** [comment]
I checked this and indeed works great. Thanks Laura!
