### ISSUE TITLE
[Feature] correct BMI calculation

### ISSUE THREAD

**Issue by corina444** [rodekruis/cashpo#42]
**Is your feature request related to a problem? Please describe.**
Right now the BMI is not calculated correctly. Change this so it's accurate. 
**User Story**
As a HRC health provider
I want to view the correct BMI 
So that I can provide health care accoringly.

**Describe the solution you'd like**

**Describe alternatives you've considered**
Correct the calculation for the BMI. The BMI for metric system is calculated based on the formula: https://www.google.com/search?q=bmi+formula&client=firefox-b-d&sxsrf=APq-WBt_W1hcqUDfS28ULU3RelynrC4o3A:1650884703286&tbm=isch&source=iu&ictx=1&vet=1&fir=UjNlJxPLd_tSJM%252CHL3S8s5-wJXBpM%252C_%253BXb1PA9ZHcMq1MM%252CXWwKLRZJ98m3wM%252C_&usg=AI4_-kSg6ATg2eDZK51RBouVopEmNXLmgQ&sa=X&ved=2ahUKEwinrrfiiK_3AhWF_6QKHbFUDi4Q_h16BAghEAE&biw=2287&bih=1108&dpr=0.9#imgrc=UjNlJxPLd_tSJM

**Comment by LauraMedendorp** [comment]
I changed the formula and the calculation seems right now.

**Comment by corina444** [comment]
This is solved!
