### ISSUE TITLE
[Feature] show BMI bumber with max 2 decimal digits

### ISSUE THREAD

**Issue by corina444** [rodekruis/cashpo#43]
**Is your feature request related to a problem? Please describe.**
Right now the BMI number is shown with a lot of decimal digits. This is unnecessary and confusing. 

**User Story**
As a HRC health provider
I want to view only a few numbers of the BMI 
So that I can quickly process this info in my head and provide appropriate healthcare. 

**Describe the solution you'd like**
Restrict the decimal digits used for the BMI to 2.

**Comment by LauraMedendorp** [comment]
Changed the formula and the BMI number now only has two digits.

**Comment by corina444** [comment]
This is solved!
