### ISSUE TITLE
[Feature] add covid-19 vaccine to vaccine dropdown list

### ISSUE THREAD

**Issue by corina444** [rodekruis/cashpo#44]
**Is your feature request related to a problem? Please describe.**
Currrently there is no covid-19 vaccine to select from Vaccination Type list. 

**User Story**
As a HRC health provider
I want to select the covid-19 vaccine option from the Vaccine Type dropdown list.
So that I can register that the individual received this vaccine. 

**Describe the solution you'd like**
Add the covid-19 vaccine to the drop down list in Vaccination Type.

**Comment by LauraMedendorp** [comment]
Added covid-19 as a Vaccination Type to the list

**Comment by corina444** [comment]
I googled the official name of the vaccine, which is all capital letters so I changed the field name to that and I also put it at the top of the vaccine list, to follow the alphabetical order.
