### ISSUE TITLE
[Feature] remove immunization from Visit Reason

### ISSUE THREAD

**Issue by corina444** [rodekruis/cashpo#45]
**Is your feature request related to a problem? Please describe.**
Whereas we already have "Vaccinations" as a separate entity, we can still select "Immunization" for visit reason. This is wrong and needs to be removed as we only want 1 way of adding vaccines, through the entity "vaccinations". 

**User Story**
As a HRC health worker
I want to select the vaccination I administered to the individual from the 
So that I keep track of their immunization history.

**Describe the solution you'd like**
Remove the option "Immunization" from the "Visit reason" field.

**Comment by LauraMedendorp** [comment]
I removed visit reason _immunization_ as option from the VisitReason

**Comment by corina444** [comment]
Laura fixed this, so I am closing this issue.
