### ISSUE TITLE
[Feature] remove 'Vaccine" from title of Treatment

### ISSUE THREAD

**Issue by corina444** [rodekruis/cashpo#46]
**Is your feature request related to a problem? Please describe.**
Right now when creating a visit you see in the title of Treatment section "Treatment (Medication, Vaccine, Laboratory Test)" but since vaccine is a separate entity now we should remove it. 

**User Story**
As a HRC health worker
I want to choose the vaccine administration from the profile and not the visit 
So that I can keep track of the vaccination history of the individual.

**Describe the solution you'd like**
the title of Treatment section should say "Treatment (Medication, Laboratory Test)" so we have to remove "Vaccine" from the title.

**Comment by LauraMedendorp** [comment]
I changed the title

**Comment by corina444** [comment]
In the end I remove the "treatment" section entirely and I added the medication and laboratory test as options in the section "I want to add the following information in the system:".
