### ISSUE TITLE
[Feature] put all bodily systems are in list of diagnosis (new visit)

### ISSUE THREAD

**Issue by corina444** [rodekruis/cashpo#47]
**Functional or Technical Spike**
Functional are used to analyse overall solution behaviour (more [info](https://www.scaledagileframework.com/spikes/))

**User Story**
As a HRC health worker
I want to choose the bodily system in which I diagnosed a problem
So that I accurately note the diagnosis

**Acceptance Criteria**
Decision: do we need to add more bodily systems to the diagnosis list? 
If yes: create new issue for feature to add those systems.
If no: close issue. 
Note: to check, have look at the current kobo form.

**Acceptance criteria**
all features from excel are now in the list. 

**Timebox**
30 m

LInk to data of form:
https://rodekruis.sharepoint.com/sites/team-Cash-IM-Greece-510/_layouts/15/guestaccess.aspx?guestaccesstoken=H31Z4wUdYlrH5eE%2FLuFhKrHoMyAaYJuS3AumabZdWL8%3D&docid=2_0c14a9a1de26846bfb981dfaf669c89b7&rev=1&e=xHHnUX

**Comment by LauraMedendorp** [comment]
I added all diagnosis to the system

**Comment by corina444** [comment]
I need to check with the head of HRC health team if we can get one or more doctors to check the lists and add more diagnoses if needed. I made a new feature for that. I will close this issue once I confirm that we have the complete list of diagnoses in the system.

**Comment by LauraMedendorp** [comment]
I did not yet add them in the layout of visit, but did that now.

**Comment by LauraMedendorp** [comment]
@corina444 What do you mean?

**Comment by corina444** [comment]
I checked this and everything is in the system! I made also the following changes:
-added "Venous Thrombosis (unspec. site)" as a diagnosis of Circulatory system
-corrrected a typo in "intestinal malabsorption"
-corrected a typo in "Suspicion Sexual Gender Based Violence (SGBV)"
-added "Loiasis" as a diagnosis in Infectious and parasitic
-corrected a typo in "Relapsing fever (borreliosis)"
-corrected a typo in "Intellectual Disabilities"
-corrected a typo in "Hodgkin's disease, lymphomas and leukaemias"
-corrected a typo in "Malignant neoplasm of cervix uteri"
-corrected a typo in "Epilepsy/ seizures"
-corrected a typo in "Diphtheria"
-corrected a typo in "Rhinitis and rhinopharyngitis"
-added "Whooping cough (pertussis)" to diagnosis respiratory system
-corrected a typo in "Inflamation of the eyelid"
-added "Wounds" to diagnosis skin
