### ISSUE TITLE
[Feature] + to add new visit go to full form immediately

### ISSUE THREAD

**Issue by corina444** [rodekruis/cashpo#54]
**Is your feature request related to a problem? Please describe.**
To view the full form for a new visit, right now you have an intermediate step with a "full form". I

**User Story**
As a HRC health worker
I want to immediately see the full form of a new visit for an individual when I click on the + sign
So that I can add the necessary information of that individual in the form. 

**Describe the solution you'd like**
It would be very useful if we didn't have this intermediate step of the "small form" but instead directly went to the full form by clicking on the + sign in the section "Visits" under the profile of an individual. 

If this is feasible, please mark issue #61  as done, because then it's not needed any longer.

**Comment by LauraMedendorp** [comment]
@corina444 The description is not provided here

**Comment by corina444** [comment]
> 

I added the information in the description.

**Comment by LauraMedendorp** [comment]
It seems like this is quite some work. Therefore, we put this back on the backlog and focus on item 61.

**Comment by corina444** [comment]
Will close this, as it's not feasible.
