### ISSUE TITLE
[Feature] check during pilot if any diagnoses are missing

### ISSUE THREAD

**Issue by corinamarkodimitraki** [rodekruis/cashpo#60]
**Is your feature request related to a problem? Please describe.**
I want to make sure no diagnosis type is missing from the list of available diagnoses per bodily regulatory system. 

**User Story**
As a HRC health care worker 
I want to have a complete list of possible diagnosis per regulatory system
So that I can add the correct diagnosis for my patient. 

**Describe the solution you'd like**
I want to check with a HRC doctor if the diagnoses we currently include per regulatory system is enough or if we are missing some diagnoses.  

**Additional context**
Perhaps we will need to ask a specific doctor specialized per regulatory system but I need to discuss with Ioanna.

**Comment by corina444** [comment]
Discussed on 2022.05.06 with Ioanna Fotopoulou that's it's best to check this when we are in Athens for the pilot.
