### ISSUE TITLE
[BUG] incorrect form appears when I click "create visit", before going to "Full form" (ignore this if issue #54 proves successful!)

### ISSUE THREAD

**Issue by corina444** [rodekruis/cashpo#61]
**Describe the bug**
A half-updated form appears when I click on the + sign to create a new visit. Some fields are correct, but some sections and fields, such as "Treatment" and "Referrals" are old and not in line with the new "full form". 

**To Reproduce**
1. Go to 'individuals'
2. Click on a random individual
3. Scroll down to "Visits"
4. Click on the + sign
5. See the half-full form that is outdate.

**Expected behavior**
We should be able to see latest form, albeit in a smaller, more concise format. 

**Screenshots**
See screenshot 
<img width="1440" alt="Screenshot 2022-05-05 at 13 45 59CEST" src="https://user-images.githubusercontent.com/60880112/166917226-3873fb48-c407-4a04-805b-950033394c8a.png">

**Desktop (please complete the following information):**
 - OS: [mac iOS]
 - Browser [firefox]
 - 
**Additional context**
To check what is the "correct form" you can click on "Full form".

**Comment by LauraMedendorp** [comment]
Discussed with Corina and I will check if it is possible to skip the small form but directly go to the full screen form. In that way this is not an issue and it looks nicer.

**Comment by LauraMedendorp** [comment]
I made the small details page of Visit identical with the details page.  I also looked at individuals and vaccinations and at both the details small and details are not identical. I think it is good to also change this.
