### ISSUE TITLE
[Feature] Make treatmentDeliveryUnit appear only if person doesn't have AMKA 

### ISSUE THREAD

**Issue by corina444** [rodekruis/cashpo#65]
**Is your feature request related to a problem? Please describe.**
Not a problem, but improving the system

**User Story**
As a HRC health worker
I want to add the form of medication from the Red Cross stock that I gave to the individual with no social security number
So that I can keep track of the administered medicine from the Red Cross stock.

**Describe the solution you'd like**
I would like the field "treatmentDeliveryUnit" to appear in the medication section only if the individual has a social security number (called AMKA in Greece). This information is already in the system under the entity "Contact" and specifically the field "amkaHas". 

**Describe alternatives you've considered**
I have tried adding a condition in the "treatmentDeliveryUnit" field, but I can't link the field "amkaHas" (from the entity "Contact") to the field "treatmentDeliveryUnit" from the entity "Visit". 

**Additional context**
I am not sure if there is a way to do this.

**Comment by LauraMedendorp** [comment]
Build the connection between having a AMKA and TreatmentDeliveryUnit, however, oly after saving the visit, it is verified whether a individual has a AMKA and thus whether the TreatmentDeliveryUnit should be required. It does not seem doable to directly verify this. 
Therefore I will for now deleted the connection.

**Comment by corina444** [comment]
Agreed that it's no use if we only see this info after saving the visit. I would suggest we just train people to use the system and only fill in this field if they have seen in the personal details page, that the individual doesn't have AMKA.
