### ISSUE TITLE
[SPIKE] add personal info in new visit

### ISSUE THREAD

**Issue by corina444** [rodekruis/cashpo#67]
**Technical Spike**
Technical are used to research various approaches in the solution domain (more [info](https://www.scaledagileframework.com/spikes/))

**User Story**
As a HRC health worker
I want to have an overview of the personal details of my patient while I am adding information on their visit page
So that I can take all this information into account for my treatment.

**Is your feature request related to a problem? Please describe.**
Right now when the health worker adds a "new visit" they cannot see the "contact details" of the person they are treating (they can only see them before they make a new visit). This would be handy for the doctor to see which languages the person speaks and if they have a social security number or not. See screenshot attached. How it is right now, VS how I would like it to be ideally. 

**Acceptance Criteria**
I would like to know if it's possible to see the "overview" of the patient in the "new visit" form, in the same way it's shown in the profile of the individual before you make a new visit. Tijs says it will be complicated but we can still investigate if this is feasible. The acceptance criteria of the spike would be a clear "yes" or "no" as an answer if this is technically feasible. 
if no -> end issue here
if yes -> make new ticket with feature to implement this change. 

**Timebox**
1 hr

![Screenshot 2022-05-10 at 12 38 02CEST](https://user-images.githubusercontent.com/60880112/167610894-634aab4a-abb8-4413-a5cd-3ac1cbc0aba3.png)
![Screenshot 2022-05-10 at 12 41 27CEST](https://user-images.githubusercontent.com/60880112/167610915-4ace3152-ea09-4009-beec-f3681c10f8d7.png)

**Comment by LauraMedendorp** [comment]
When adding a new visit, it is not possible to see contact details. When saving the visit and then editing it again, it is possible. It seems like only when saving for which individual the visit will be, will make it possible to see this information.

**Comment by corina444** [comment]
Thanks for checking @LauraMedendorp! I would then suggest that you reverse the system back to how it was (so undo these changes), and then we leave it to the training to do its job and get doctors used to the fact that they have to check this info in the patient profile. They can also open this in another tab.

**Comment by LauraMedendorp** [comment]
I put everything like it was before. I think this item can be closed now.

**Comment by corina444** [comment]
Thanks! Closing this issue now.
