### ISSUE TITLE
[Feature] Required field have an already chosen default option

### ISSUE THREAD

**Issue by LauraMedendorp** [rodekruis/cashpo#68]
For serveral fields that are required, a default option is already filled-in. In this way, when the user is not reminded that this field should be filled in and the default is not the right option, mistakes could be made. 

Investigate in which way this can be fixed.

**Comment by corina444** [comment]
Thanks for looking into this! I think multi-enum can work, but not for all fields. I see the following solutions, all of which I suggest we implement (will create new feature requests for these). 

1. Change the following fields from "enum" to "multi-enum": 
VISIT > Visit type > Visit type, Clinic type
VISIT> Medication > Unit of Measurement, Form of medication, Location of Medication Administration
VACCINATIONS > Vaccination type, Vaccination dose, Vaccination supplier.

2. we add an option to all other "enum" fields. The option will ask the user to add info to this field, similarly to the the option "add clinic type" in the field "Clinic type". This way it will be clear to the user that they have to fill something in.

3. people are properly trained to always choose an option. 

Closing this issue and opening new feature requests for the changes described above.
