### ISSUE TITLE
[SPIKE] automated import of data gathered with Kobo

### ISSUE THREAD

**Issue by corina444** [rodekruis/cashpo#70]
**Functional or Technical Spike**
technical are used to research various approaches in the solution domain (more [info](https://www.scaledagileframework.com/spikes/))

**User Story**
As a HRC IT worker
I want to import the collected data of all treated individuals automatically
So that I save time

**Acceptance Criteria**
Decision: is it possible to automate the import of data of individuals so far gathered by HRC?
If yes: close this issue and create feature spikes to solve this.
If no: close this issue and create training to help people import data correctly. 

**Timebox**
2-3 hrs. It is worth investing in this in time now, because it could save loads of time for the HRC team.

**Comment by LauraMedendorp** [comment]
Yes, it seems possible to import data from a CSV file. A CSV file is a excel file. I think Kobo can be transferred into excel? In that case it is possible. Explanation can be found here: https://docs.espocrm.com/administration/import/

**Comment by corina444** [comment]
That's really great! Looks like we can give them this option during the sprint 2 review. I will have to check with Lars if import of these data falls within our responsibilities. In any case, we have enough hrs on the project to do it ourselves if we can. I will close this issue for now, and create a new issue in the "pilot" backlog to import the records to date.
