### ISSUE TITLE
[Feature] import individual records to date in system

### ISSUE THREAD

**Issue by corinamarkodimitraki** [rodekruis/cashpo#72]
**Is your feature request related to a problem? Please describe.**
The HRC needs to import thousands of records of individuals in the new CRM system which is costly in time and HR. We can solve this issue by automating the process.

**User Story**
As a HRC worker
I want to view the records to date in the CRM system
So that I use one system for all records.

**Describe the solution you'd like**
All data recorded till now need to be imported in the CRM system. We will need to check which fields are matching between the CRM system and the excels (kobo) and which are not matching. For the ones not matching, we will need to see if the information is needed, and if so, how to import it in the CRM system anyways. I suggest enabling the parameter "check for duplicates" during import. 

**Describe alternatives you've considered**
The HRC health team suggested they train people to do the import by hand, but I strongly support automated import. 

Note: the import can only take place once HRC leadership has agreed on launching the system HRC health-wide. The moment of decision would be after the pilot.

**Comment by tijsziere** [comment]
possible, needs a bit of time, when would we need to do this? just before the pilot? Or before the presentation?

**Comment by corina444** [comment]
Before the pilot, so we have time @tijsziere

**Comment by leoniecazemier** [comment]
Some notes from importing: 

- Firstname/lastname order is not alway the same in Kobo, so firstname/lastname might be switched for some individuals.
- People with no first/last name I've called Name/Unknown
- Unknown birthdays/birthyears I've put to 01/01/1900
- Some vaccinations were given to individuals whose HRC code is not in the BHCU registration.
