### ISSUE TITLE
[Feature] change field "duration of visit"

### ISSUE THREAD

**Issue by corinamarkodimitraki** [rodekruis/cashpo#75]
**Is your feature request related to a problem? Please describe.**
Right now the user can only choose from a pre-defined list what the duration time was, but the list doesn't contain a lot of options. I think it's best to give the user the freedom to add the time manually.

**User Story**
As a HRC health worker
I want to add the real total duration time of the visit
So that I insert true information into the system.

**Describe the solution you'd like**
1. Split the duration field into two fields: Duration (free text) and unit of time (multi-enum, with options "hour" and "minutes"). 
2. Change the small form accordingly.

**Describe alternatives you've considered**

**Comment by corina444** [comment]
Changed this section to enter number of minutes or hours and a list to select the unit of measurement of time from.
