### ISSUE TITLE
[Feature] add option to enum fields

### ISSUE THREAD

**Issue by corina444** [rodekruis/cashpo#77]
**Is your feature request related to a problem? Please describe.**

**User Story**
As a HRC health worker
I want to be reminded to choose an option from a list
So that I don't forget to enter important information in the system

**Describe the solution you'd like**
Add an option to all "enum" fields that are not mentioned in issue #76 . The option will ask the user to add info to this field, similarly to the the option "add clinic type" in the field "Clinic type". This way it will be clear to the user that they have to fill something in. Τhe option will need to be very concise and make it clear that the user has to choose an option from the list.

**Comment by corina444** [comment]
Add empty option in fields "unit of measurement" and "form of medication" and other not required fields.

**Comment by LauraMedendorp** [comment]
All required fields got: fill in X 
Not required fields have a empty default

**Comment by corina444** [comment]
Perfect, thanks Laura!
