### ISSUE TITLE
[Feature] remove icons in the dots in left menu

### ISSUE THREAD

**Issue by corinamarkodimitraki** [rodekruis/cashpo#79]
**Is your feature request related to a problem? Please describe.**
Right now the icons that are available when you click on the dots on the left menu, are irrelevant so they can be removed.

**User Story**
As a HRC worker
I want to not have to click on extra things to make icons appear
So that I have a clear view of the options I can click on at a glance

**Describe the solution you'd like**
Remove the icons in the three dots, they are irrelevant.

**Comment by corina444** [comment]
Completed this.
