### ISSUE TITLE
[Feature] Add referral types in dashboard

### ISSUE THREAD

**Issue by corinamarkodimitraki** [rodekruis/cashpo#84]
**Is your feature request related to a problem? Please describe.**
The HRC needs to report on numbers of all the types of referrals they give. Right now the dashboard only shows the total number of referrals, not distinguishing by type.

**User Story**
As a HRC reporting staff 
I want to view the number of referrals on the dashboard by type
So that I can report this information as asked. 

**Describe the solution you'd like**
Add to the dashboard referral numbers per type. The types of referrals are: 
1. ACCREF
2. Emergency Referral
3. Hospital
4. Other NGO Health Services
5. Hellenic Red Cross Doctor
6. Left Against Medical Advice (LAMA)
7. PSS/Social Work
8. P.F.Y or D.F.Y.

**Comment by corina444** [comment]
I added 3 referrals to 3 individuals (total referrals should be 22) to check if the dashboard updates but it only shows records up until May. Can we change it @tijsziere to show all the records?
