### ISSUE TITLE
[SPIKE] import of HRC health Kobo data into EspoCRM

### ISSUE THREAD

**Issue by corinamarkodimitraki** [rodekruis/cashpo#95]
**Technical Spike**
Technical are used to research various approaches in the solution domain (more [info](https://www.scaledagileframework.com/spikes/))

**User Story**
As a NLRC collaborator of HRC
I want to know exactly how to import the current HRC kobo data into Espo CRM
So that I can easily do the import when I am in Athens for the pilot.

**Acceptance Criteria**
A document describing a step-by-step workflow of how to import the HRC kobo data into EspoCRM. 
the data of visits and vaccinations should be linked to individuals. This part is not worked out in this document yet. If it is not clear how this should be done

**Timebox**
6h gok ik? Maar kijk maar hoelang je nodig hebt

**Comment by corina444** [comment]
Check if imported visits and vaccinations are linked to individuals. Create some dummy visit and vaccination data and check what settings work.

**Comment by leoniecazemier** [comment]
I've added the linking of individuals with other records in espo and updated the import instructions. I will update the instructions if I find errors in the future.
